[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 200
via_ir = true

# RPC endpoints
[rpc_endpoints]
polygon_amoy = "${ALCHEMY_Amoy_RPC_URL}"

# Etherscan API configuration
[etherscan]
polygon_amoy = { key = "${ETHERSCAN_API_KEY}" }